name: Check
on: [push, pull_request]
jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo fmt --check
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Tests
        run: cargo test
